spring:
  application:
    name: user-service
#  profiles:
#    active: test
server:
  port: 9092
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:10086/eureka/
test:
  xc
